python: python.cluster_methods.cluster_profile Namespace Reference
python.cluster_methods.cluster_profile Namespace Reference
Functions
def get_points
Get number density of points along the projected radius of the cluster.
def confidence
Get confidence limits for best-fit scale radius.
def nfw_best_fit
Minimisation of projected NFW with background density using adaptive grid search.
Function Documentation
def python.cluster_methods.cluster_profile.confidence (r_scale, bg_density, R_proj, grid, dof)
Get confidence limits for best-fit scale radius.
Parameters
[in] r_scale Best scale radius.
[in] bg_density Best background density.
[in] R_proj Projected radius.
[in] grid Number of grid points.
[in] dof Degree of freedom.
Returns
Lower and upper confidence limits.
References python.cluster_methods.cluster_profile.nfw_best_fit().
def python.cluster_methods.cluster_profile.get_points (R_proj, num_points, weights)
Get number density of points along the projected radius of the cluster.
Adapated from profmaxliknfwp.pro IDL script by A. Biviano.
Parameters
[in] R_proj Projected radius.
[in] num_points Number of points
[in] weights Optional weights.
Returns
Projected radius, projected density and errors.
References python.biviano_py.biweight.bwtav(), and python.quick_hist.range.
def python.cluster_methods.cluster_profile.nfw_best_fit (R_proj, r_scale_ini, grid, bg_density_ini = 0.0, fit_bg = True, fpb = 1, weights = None)
Minimisation of projected NFW with background density using adaptive grid search.
Adapated from profmaxliknfwp.pro IDL script by A. Biviano.
Parameters
[in] R_proj Projected radius.
[in] r_scale_ini Initial scale radius.
[in] grid Number of grid points.
[in] bg_density_ini Initial background density.
[in] fit_bg Option to fit background.
[in] fpb Factor?
[in] weights Optional weights.
Returns
Best-fit scale radius and background density, projected density points with errors, fit to data and chi-squared test results.
References python.functions.stats.chi2_gof(), python.cluster_methods.cluster_profile.confidence(), python.cluster_methods.cluster_profile.get_points(), and python.halo_methods.nfw.nfw_num_density().