python: python.web_code.robust Namespace Reference
python.web_code.robust Namespace Reference
Functions
def biweightMean
def mean
def std
def checkfit
def linefit
def polyfit
Variables
string __version__ = '0.3'
string __revision__ = '$Rev$'
list __all__ = ['biweightMean', 'mean', 'std', 'checkfit', 'linefit', 'polyfit', '__version__', '__revision__', '__all__']
int __iterMax = 25
float __delta = 5.0e-7
float __epsilon = 1.0e-20
Function Documentation
def python.web_code.robust.biweightMean (inputData)
Calculate the mean of a data set using bisquare weighting.
Based on the biweight_mean routine from the AstroIDL User's
Library.
References python.web_code.robust.std(), and python.analyz2.type.
def python.web_code.robust.checkfit (inputData, inputFit, epsilon, delta, BisquareLimit = 6.0)
Determine the quality of a fit and biweights.  Returns a tuple
with elements:
  0. Robust standard deviation analog
  1. Fractional median absolute deviation of the residuals
  2. Number of input points given non-zero weight in the calculation
  3. Bisquare weights of the input points
  4. Residual values scaled by sigma
This function is based on the rob_checkfit routine from the AstroIDL
User's Library.
References python.web_code.robust.std(), and python.analyz2.type.
def python.web_code.robust.linefit (inputX, inputY, iterMax = 25, Bisector = False, BisquareLimit = 6.0, CloseFactor = 0.03)
Outlier resistance two-variable linear regression function.
Based on the robust_linefit routine in the AstroIDL User's Library.
References python.web_code.robust.checkfit(), and python.analyz2.type.
def python.web_code.robust.mean (inputData, Cut = 3.0)
Robust estimator of the mean of a data set.  Based on the
resistant_mean function from the AstroIDL User's Library.
.. seealso::
    :func:`lsl.misc.mathutil.robustmean`
References python.analyz2.type.
def python.web_code.robust.polyfit (inputX, inputY, order, iterMax = 25)
Outlier resistance two-variable polynomial function fitter.
Based on the robust_poly_fit routine in the AstroIDL User's
Library.
Unlike robust_poly_fit, two different polynomial fitters are used
because numpy.polyfit does not support non-uniform weighting of the
data.  For the weighted fitting, the SciPy Orthogonal Distance
Regression module (scipy.odr) is used.
References python.web_code.robust.checkfit(), python.quick_hist.range, and python.analyz2.type.
def python.web_code.robust.std (inputData, Zero = False)
Robust estimator of the standard deviation of a data set.
Based on the robust_sigma function from the AstroIDL User's Library.
References python.web_code.robust.mean(), and python.analyz2.type.
Variable Documentation
list python.web_code.robust.__all__ = ['biweightMean', 'mean', 'std', 'checkfit', 'linefit', 'polyfit', '__version__', '__revision__', '__all__']
float python.web_code.robust.__delta = 5.0e-7
float python.web_code.robust.__epsilon = 1.0e-20
int python.web_code.robust.__iterMax = 25
string python.web_code.robust.__revision__ = '$Rev$'
string python.web_code.robust.__version__ = '0.3'