python: mem_match.pydiag2 Namespace Reference
mem_match.pydiag2 Namespace Reference
Functions
def usage
def file_name_error
def get_rich
def find_galaxy_match
def find_halo_match
def loop_through_matches
def nan2one
def main
Function Documentation
def mem_match.pydiag2.file_name_error (file_name)
Function that returns an error message for missing files
References mem_match.pydiag2.usage().
def mem_match.pydiag2.find_galaxy_match (cluster_galaxy_ids, mock_galaxy_ids)
Function to match galaxy IDs between cluster files and mocks
def mem_match.pydiag2.find_halo_match (halo_ids, cluster_ids, cluster_now)
Function to find the most common Halo ID associated to a given cluster
def mem_match.pydiag2.get_rich (galaxy_list, unique_galaxy_list)
Function to determine richness of a given halo/cluster
References python.quick_hist.range.
def mem_match.pydiag2.loop_through_matches (halo_ids, cluster_ids, unique_cluster_ids)
Function that loops through all cluster to halo matches
References mem_match.pydiag2.find_halo_match(), and python.quick_hist.range.
def mem_match.pydiag2.main (argv)
References mem_match.pydiag2.file_name_error(), mem_match.pydiag2.find_galaxy_match(), mem_match.pydiag2.get_rich(), mem_match.pydiag2.loop_through_matches(), mem_match.pydiag2.nan2one(), python.quick_hist.range, and mem_match.pydiag2.usage().
def mem_match.pydiag2.nan2one (array)
Convert nan values to 1.0
def mem_match.pydiag2.usage ()
Function that prints basic code usage.