python: guess Namespace Reference
guess Namespace Reference
Functions
def init
def create_1000_color_lines
def clear_1000_color_lines
def color_bar_guesses
def restore_color_bar
def clear_color_bar
def range100
def range1000
def rb_handler
def get_input
Variables
tuple root = Tk()
tuple frame1 = Frame(root)
tuple frame_spacer_c0 = Frame(root)
tuple frame_spacer_c1 = Frame(root)
tuple canvas = Canvas(root,width=330, height=600, bg='white')
int num_range = 100
int num_guesses = 0
int BAR_WIDTH = 60
string F_HEL_12 = "Helvetica 12"
string V6 = "Verdana 8"
string LIGHT_PINK = '#FFB6C1'
string SKYBLUE = '#87CEEB'
string LIGHTGREEN = '#90EE90'
string DARKORANGE = '#FF8C00'
string GOLD = '#FFD700'
string YELLOW = '#FFFF00'
string LIME = '#00FF00'
string LAWNGREEN = '#7CFC00'
string YELLOWGREEN = '#9ACD32'
string PALETURQUOISE = '#AFEEEE'
string ROYALBLUE = '#4169E1'
int BOTTOM_Y = 540
int TOP_Y = 240
int LEFT_X = 200
int RIGHT_X = 260
tuple MID_X = (LEFT_X + RIGHT_X)
int LAB_WIDTH = 20
int BOX_WIDTH = 12
int top_spacing = 5
tuple Lblank_top_c0 = Label(frame_spacer_c0, text=" ")
tuple Lblank_top_c1 = Label(frame_spacer_c1, text=" ")
tuple Lblank0_vert = Label(frame1, text=" ")
tuple text_label = Label(frame1, text="'Guess the Number' game\n \n 6 guesses between 0-99\n 9 guesses between 0-999")
tuple Lblank2 = Label(frame1, text=" ")
tuple rb_var = IntVar()
tuple rb_r100
tuple rb_r1000
tuple Lblank = Label(frame1, text=" ")
tuple L_enter_guess = Label(frame1, text="Enter your guess:")
tuple entry_box = Entry(frame1, width=BOX_WIDTH)
tuple Lblank_vert = Label(frame1, text=" ")
tuple t_lower = canvas.create_text(60,40 , text = " ", font = V6, anchor = 'e')
tuple t_won = canvas.create_text(50, 580, text = " ", font = F_HEL_12, anchor = 'sw')
tuple t_message = canvas.create_text(50, 590, text = " ", font = F_HEL_12, anchor = 'sw')
tuple t_upper = canvas.create_text(60,40 , text = " ", font = V6, anchor = 'e')
tuple box_guesses = canvas.create_rectangle(LEFT_X, TOP_Y, RIGHT_X, BOTTOM_Y, width = 2.0)
Function Documentation
def guess.clear_1000_color_lines ()
clears the extra lines and color boxes for the 0-1000 mode 'guesses left' countdown
def guess.clear_color_bar ()
clears first 6 blocks of color bar for tracking remaining guesses
def guess.color_bar_guesses (num_guesses)
turns off a color block when a guess is made - shows # guesses left
def guess.create_1000_color_lines ()
extend box and colors for 0-1000 mode 'guesses left' countdown
def guess.get_input (guess)
takes user's guess and compares to computer's random number
References clear_1000_color_lines(), color_bar_guesses(), and init().
def guess.init ()
initialize first game or restart subsequent games
References clear_1000_color_lines(), clear_color_bar(), create_1000_color_lines(), python.quick_hist.range, and restore_color_bar().
def guess.range100 ()
References clear_1000_color_lines(), clear_color_bar(), and init().
def guess.range1000 ()
References clear_1000_color_lines(), clear_color_bar(), and init().
def guess.rb_handler ()
radiobutton handler ... calls range100() or range1000()
References range100(), and range1000().
def guess.restore_color_bar ()
restores color bar for tracking remaining guesses
Variable Documentation
int guess.BAR_WIDTH = 60
int guess.BOTTOM_Y = 540
tuple guess.box_guesses = canvas.create_rectangle(LEFT_X, TOP_Y, RIGHT_X, BOTTOM_Y, width = 2.0)
int guess.BOX_WIDTH = 12
tuple guess.canvas = Canvas(root,width=330, height=600, bg='white')
string guess.DARKORANGE = '#FF8C00'
tuple guess.entry_box = Entry(frame1, width=BOX_WIDTH)
string guess.F_HEL_12 = "Helvetica 12"
tuple guess.frame1 = Frame(root)
tuple guess.frame_spacer_c0 = Frame(root)
tuple guess.frame_spacer_c1 = Frame(root)
string guess.GOLD = '#FFD700'
tuple guess.L_enter_guess = Label(frame1, text="Enter your guess:")
int guess.LAB_WIDTH = 20
string guess.LAWNGREEN = '#7CFC00'
tuple guess.Lblank = Label(frame1, text=" ")
tuple guess.Lblank0_vert = Label(frame1, text=" ")
tuple guess.Lblank2 = Label(frame1, text=" ")
tuple guess.Lblank_top_c0 = Label(frame_spacer_c0, text=" ")
tuple guess.Lblank_top_c1 = Label(frame_spacer_c1, text=" ")
tuple guess.Lblank_vert = Label(frame1, text=" ")
int guess.LEFT_X = 200
string guess.LIGHT_PINK = '#FFB6C1'
string guess.LIGHTGREEN = '#90EE90'
string guess.LIME = '#00FF00'
tuple guess.MID_X = (LEFT_X + RIGHT_X)
int guess.num_guesses = 0
int guess.num_range = 100
string guess.PALETURQUOISE = '#AFEEEE'
tuple guess.rb_r100
Initial value:
 = Radiobutton(frame1, text = "Range = [0,100)", width = LAB_WIDTH,
 value = '100', variable = rb_var, command = rb_handler, indicatoron = 0)
tuple guess.rb_r1000
Initial value:
 = Radiobutton(frame1, text = "Range = [0,1000)", width = LAB_WIDTH,
 value = '1000', variable = rb_var, command = rb_handler, indicatoron = 0)
tuple guess.rb_var = IntVar()
int guess.RIGHT_X = 260
tuple guess.root = Tk()
string guess.ROYALBLUE = '#4169E1'
string guess.SKYBLUE = '#87CEEB'
tuple guess.t_lower = canvas.create_text(60,40 , text = " ", font = V6, anchor = 'e')
tuple guess.t_message = canvas.create_text(50, 590, text = " ", font = F_HEL_12, anchor = 'sw')
tuple guess.t_upper = canvas.create_text(60,40 , text = " ", font = V6, anchor = 'e')
tuple guess.t_won = canvas.create_text(50, 580, text = " ", font = F_HEL_12, anchor = 'sw')
tuple guess.text_label = Label(frame1, text="'Guess the Number' game\n \n 6 guesses between 0-99\n 9 guesses between 0-999")
int guess.top_spacing = 5
int guess.TOP_Y = 240
string guess.V6 = "Verdana 8"
string guess.YELLOW = '#FFFF00'
string guess.YELLOWGREEN = '#9ACD32'