python: python.biviano_py.profmaxliknfwp Namespace Reference
python.biviano_py.profmaxliknfwp Namespace Reference
Functions
def nfw_proj_sd
def nfw_proj_mass
def nfw_pbkd_maxlik
def min_nfwp
def profmaxliknfwp
Function Documentation
def python.biviano_py.profmaxliknfwp.min_nfwp (rp, cr, bkd, a)
Minimization of pNFW with bkd using adaptive grid search
References python.biviano_py.profmaxliknfwp.nfw_pbkd_maxlik(), and python.quick_hist.range.
def python.biviano_py.profmaxliknfwp.nfw_pbkd_maxlik (rp, cr, bkd, a)
References python.biviano_py.profmaxliknfwp.nfw_proj_mass().
def python.biviano_py.profmaxliknfwp.nfw_proj_mass (t)
NFW projected mass along a cylinder in units of M(r-2).
From equation B1 in Appendix B in Mamon, Biviano, Boue 2013.
t is a radius in units of rs (or r-2).
def python.biviano_py.profmaxliknfwp.nfw_proj_sd (t)
NFW profile projected surface density from eqs. (42,43) in
Lokas + Mamon 2001, MNRAS, 321, 155.
t = R / r_s is the radius in unit of r_s (= r - 2)
def python.biviano_py.profmaxliknfwp.profmaxliknfwp (rmpc, comp, fpb, parinp, npfree, grid)
Max Lik fit to number density profile (projected NFW)
with or without background
References python.biviano_py.profmaxliknfwp.min_nfwp(), python.biviano_py.profmaxliknfwp.nfw_pbkd_maxlik(), python.biviano_py.profmaxliknfwp.nfw_proj_mass(), and python.quick_hist.range.