python: astro Namespace Reference
astro Namespace Reference
Functions
def check_ra
Function that checks if the input right ascension is valid.
def check_dec
Function that checks if the input declination is valid.
def check_obj
Function that checks if the input object is valid.
def deg2rad
Function that converts angle from degrees to radians.
def rad2deg
Function that converts angle from radians to degrees.
def radec2xyz
Function that converts Equatorial Coordinates (RA, Dec) to Cartesian coordinates (X, Y and Z) given a distance r.
def xyz2radec
Function that converts Cartesian coordinates (X, Y and Z) to Equatorial Coordinates (RA, Dec) with a distance r.
def ang_sep
Function that calculates the angular separation in degrees between to objects.
def mag2flux
Function that converts magnitude to flux given a zero-point.
def flux2mag
Function that converts flux to magnitude given a zero-point.
Function Documentation
def astro.ang_sep (obj1, obj2)
Function that calculates the angular separation in degrees between to objects.
Parameters
[in] obj1 RA and Dec of object 1 in degrees.
[in] obj2 RA and Dec of object 2 in degrees.
Returns
Angular separation in degrees.
References check_obj(), deg2rad(), and rad2deg().
def astro.check_dec (dec)
Function that checks if the input declination is valid.
Parameters
[in] dec Input declination.
Exceptions
ValueError for invalid Dec.
def astro.check_obj (obj)
Function that checks if the input object is valid.
Parameters
[in] obj RA and Dec on input object.
References check_dec(), and check_ra().
def astro.check_ra (ra)
Function that checks if the input right ascension is valid.
Parameters
[in] ra Input right ascension.
Exceptions
ValueError for invalid RA.
def astro.deg2rad (angle)
Function that converts angle from degrees to radians.
Parameters
[in] angle Input angle in degrees.
Returns
Output angle in radians.
def astro.flux2mag (flux, zero)
Function that converts flux to magnitude given a zero-point.
Parameters
[in] flux Flux.
[in] zero Zero-point.
Returns
Magnitude.
def astro.mag2flux (mag, zero)
Function that converts magnitude to flux given a zero-point.
Parameters
[in] mag Magnitude.
[in] zero Zero-point.
Returns
Flux.
def astro.rad2deg (angle)
Function that converts angle from radians to degrees.
Parameters
[in] angle Input angle in radians.
Returns
Output angle in degrees.
def astro.radec2xyz (ra, dec, r)
Function that converts Equatorial Coordinates (RA, Dec) to Cartesian coordinates (X, Y and Z) given a distance r.
Parameters
[in] ra Right ascension in degrees.
[in] dec Declination in degrees.
[in] r Distance in given units.
Returns
X, Y and Z in units of r.
References deg2rad().
def astro.xyz2radec (x, y, z)
Function that converts Cartesian coordinates (X, Y and Z) to Equatorial Coordinates (RA, Dec) with a distance r.
Parameters
[in] x X-coordinate in given units.
[in] y Y-coordinate in given units.
[in] z Z-coordinate in given units.
Returns
Ra and Dec in degrees and r in units of X, Y and Z
References rad2deg().