python: python.pydiag2 Namespace Reference
python.pydiag2 Namespace Reference
Functions
def usage
def file_name_error
def get_rich
def find_galaxy_match
def find_halo_match
def loop_through_matches
def nan2one
def main
Function Documentation
def python.pydiag2.file_name_error (file_name)
Function that returns an error message for missing files
References python.pydiag2.usage().
def python.pydiag2.find_galaxy_match (cluster_galaxy_ids, mock_galaxy_ids)
Function to match galaxy IDs between cluster files and mocks
def python.pydiag2.find_halo_match (halo_ids, cluster_ids, cluster_now)
Function to find the most common Halo ID associated to a given cluster
def python.pydiag2.get_rich (galaxy_list, unique_galaxy_list)
Function to determine richness of a given halo/cluster
References python.quick_hist.range.
def python.pydiag2.loop_through_matches (halo_ids, cluster_ids, unique_cluster_ids)
Function that loops through all cluster to halo matches
References python.pydiag2.find_halo_match(), and python.quick_hist.range.
def python.pydiag2.main (argv)
References python.pydiag2.file_name_error(), python.pydiag2.find_galaxy_match(), python.pydiag2.get_rich(), python.pydiag2.loop_through_matches(), python.pydiag2.nan2one(), python.quick_hist.range, and python.pydiag2.usage().
def python.pydiag2.nan2one (array)
Convert nan values to 1.0
def python.pydiag2.usage ()
Function that prints basic code usage.