python: python.pycymatch_lib.pycymatch_match Namespace Reference
python.pycymatch_lib.pycymatch_match Namespace Reference
Functions
def basic_match
Find observed clusters that satisfy the basic match criteria.
def r200_match
Find observed clusters within r200 of mock halo centre.
def find_matches
Find cylindrical matches between mock haloes and observed clusters.
def mo_matrix
Produce mass-observable matrix.
def scale_matrix
Function to scale matrix lines to 1.0.
def halo_tag
Function to tag matched Haloes.
Function Documentation
def python.pycymatch_lib.pycymatch_match.basic_match (i, mock, obs, dz)
Find observed clusters that satisfy the basic match criteria.
Parameters
[in] i Index of observed cluster.
[in] mock List of mock haloes.
[in] obs List of observed clusters.
[in] dz Redshift matching treshold.
Returns
List of indices of mock haloes that satisfy the matching criteria for a given observed cluster.
def python.pycymatch_lib.pycymatch_match.find_matches (mock, obs, dz)
Find cylindrical matches between mock haloes and observed clusters.
Parameters
[in] mock List of mock haloes.
[in] obs List of observed clusters.
[in] dz Redshift matching treshold.
Returns
Indices of mathces and corresponding probabilities of mock haloes to observed clusters.
References python.pycymatch_lib.pycymatch_match.basic_match(), python.pycymatch_lib.pycymatch_match.r200_match(), and python.quick_hist.range.
def python.pycymatch_lib.pycymatch_match.halo_tag (mock, index)
Function to tag matched Haloes.
Parameters
[in] mock List of mock haloes.
[in] index List of indices of matches.
Returns
List of indeces of unique matches to mock haloes.
def python.pycymatch_lib.pycymatch_match.mo_matrix (mock, obs, opts)
Produce mass-observable matrix.
Parameters
[in] mock List of mock haloes.
[in] obs List of observed clusters.
[in] opts List of arguments.
Returns
Mass-observable matrix, histogram of all mock halo masses, histogram of matched halo masses, x-range values of halo masses, x-range values of observed cluster mass proxies.
References python.pycymatch_lib.pycymatch_match.find_matches(), python.pycymatch_lib.pycymatch_match.halo_tag(), python.pycymatch_lib.pycymatch_io.print_matches(), and python.quick_hist.range.
def python.pycymatch_lib.pycymatch_match.r200_match (i, index, mock, obs)
Find observed clusters within r200 of mock halo centre.
Parameters
[in] i Index of observed cluster.
[in] index List of indices of matches.
[in] mock List of mock haloes.
[in] obs List of observed clusters.
Returns
Indices of mathces and corresponding probabilities of mock haloes to a given observed cluster.
def python.pycymatch_lib.pycymatch_match.scale_matrix (matrix)
Function to scale matrix lines to 1.0.
Parameters
[in] matrix Input matrix.
Returns
Scaled matrix.
References python.quick_hist.range.