python: python.functions.cosmo Namespace Reference
python.functions.cosmo Namespace Reference
Functions
def angdidis
def comdis
def dcomdisdz
def dcomvoldz
def dpropmotdisdz
def propmotdis
def lumdis
Function Documentation
def python.functions.cosmo.angdidis (z, OmegaM, OmegaL)
This function calculates the angular diameter distance d_A as a
function of z, Omega_M and Omega_L in a matter-dominated universe,
using the function propmotdis().  H0=c=1
References python.functions.cosmo.propmotdis().
def python.functions.cosmo.comdis (z, OmegaM, OmegaL)
This function calculates the line-of-sight comoving distance d_C as
a function of z, Omega_M and Omega_L in a matter-dominated
universe, using dcomdisdz().  H0=c=1.
References python.functions.cosmo.dcomdisdz().
def python.functions.cosmo.dcomdisdz (z, OmegaM, OmegaL)
This function calculates the differential line-of-sight comoving
distance dD_c/dz as a function of z, Omega_M and Omega_L in a
matter-dominated universe.  H0=c=1.
def python.functions.cosmo.dcomvoldz (z, OmegaM, OmegaL)
This function calculates the one-steradian differential comoving
volume dV/dz as a function of z, Omega_M and Omega_L in a
matter-dominated universe.  Formulae from Carrol, Press & Turner,
1992, Kolb & Turner, 1990, and my own calculation.  H0=c=1.
References python.functions.cosmo.dpropmotdisdz(), and python.functions.cosmo.propmotdis().
def python.functions.cosmo.dpropmotdisdz (z, OmegaM, OmegaL)
This function calculates the derivative of the proper motion
distance d_M with respect to redshift z as a function of z, Omega_M
and Omega_L in a matter-dominated universe.  Formula from Carrol,
Press & Turner, 1992.  This function also requires the function
propmotdis(). H0=c=1.
References python.functions.cosmo.propmotdis().
def python.functions.cosmo.lumdis (z, OmegaM, OmegaL)
This function calculates the luminosity distance d_L as a function
of z, Omega_M and Omega_L in a matter-dominated universe, using the
function propmotdis().  H0=c=1.
References python.functions.cosmo.propmotdis().
def python.functions.cosmo.propmotdis (z, OmegaM, OmegaL)
This function calculates the proper motion distance d_M as a
function of z, Omega_M and Omega_L in a matter-dominated universe.
Formulae from Carrol, Press & Turner, 1992, Kolb \& Turner, 1990,
and Hogg derivation.  Makes use of comdis().  H0=c=1.
References python.functions.cosmo.comdis().