python: python.functions.comp Namespace Reference
python.functions.comp Namespace Reference
Functions
def check_min
Function that checks if the minimum value is valid.
def check_minmax
Function that checks if the minimum and maximum values are valid.
def find_bin
Function that finds the bin corresponding to a given value.
def num_bins
Function that finds the number of bins for a given range and bin size.
def x_vals
Function that the x-range values for bins in a given range.
def within
Function that the checks if the input value is within a given range.
def nan2one
Function that sets all NaN values in an array to 1.
def nan2zero
Function that sets all NaN values in an array to 0.
def scale
Feature scale data.
Function Documentation
def python.functions.comp.check_min (min_val)
Function that checks if the minimum value is valid.
Parameters
[in] min_val Minimum of bin range.
Exceptions
ValueError if min_val < 0.0.
def python.functions.comp.check_minmax (min_val, max_val)
Function that checks if the minimum and maximum values are valid.
Parameters
[in] min_val Minimum of bin range.
[in] max_val Maximum of bin range.
Exceptions
ValueError if min_val > max_val.
References python.functions.comp.check_min().
def python.functions.comp.find_bin (value, min_value, bin_size)
Function that finds the bin corresponding to a given value.
Parameters
[in] value Input value.
[in] min_value Minimum of bin range.
[in] bin_size Width of bins.
References python.functions.comp.check_min().
def python.functions.comp.nan2one (array)
Function that sets all NaN values in an array to 1.
Parameters
[in] array Input array.
def python.functions.comp.nan2zero (array)
Function that sets all NaN values in an array to 0.
Parameters
[in] array Input array.
def python.functions.comp.num_bins (min_value, max_value, bin_size)
Function that finds the number of bins for a given range and bin size.
Parameters
[in] min_value Minimum of bin range.
[in] max_value Maximum of bin range.
[in] bin_size Width of bins.
References python.functions.comp.check_minmax().
def python.functions.comp.scale (data, min_val, max_val)
Feature scale data.
Ignores division by zero.
Parameters
[in] data Input data.
[in] min_val Minimum value.
[in] max_val Maximum value.
Exceptions
ValueError if data > max_val.
References python.functions.comp.check_minmax(), and python.functions.comp.nan2zero().
def python.functions.comp.within (value, min_value, max_value)
Function that the checks if the input value is within a given range.
Parameters
[in] value Input value.
[in] min_value Minimum of bin range.
[in] max_value Maximum of bin range.
References python.functions.comp.check_minmax().
def python.functions.comp.x_vals (n_bins, min_value, bin_size)
Function that the x-range values for bins in a given range.
Parameters
[in] n_bins Number of bins.
[in] min_value Minimum of bin range.
[in] bin_size Width of bins.
References python.functions.comp.check_min().