python: python.functions.cosmo2 Namespace Reference
python.functions.cosmo2 Namespace Reference
Functions
def check_cosmo
This function checks if the cosmological parameters are valid.
def t_H
This function calculates the Hubble time T_H in Gyr.
def age
This function calculates the age of the Universe in Gyr down to a given redshift.
def d_H
This function calculates the Hubble distance D_H in Mpc.
def E
This function calculates E(z), the Hubble parameter.
def E_inv
This function calculates 1.0/E(z).
def d_comov
This function calculates the line-of-sight comoving distance D_C.
def d_prop
This function calculates the proper motion distance D_M (transverse comoving distance).
def d_angdi
This function calculates the angular diameter distance D_A.
def d_lum
This function calculates the luminosity distance D_L.
def dD_prop_dz
This function calculates the derivative of the proper motion distance with respect to redshift dD_M/dz.
def dV_comov_dz
This function calculates the one-steradian differential comoving volume dV_C/dz.
def v_comov
This function calculates the full comoving volume V_C.
def rho_crit
This function calculates the critical density rho_c.
Function Documentation
def python.functions.cosmo2.age (H_0, z, Omega_M, Omega_L)
This function calculates the age of the Universe in Gyr down to a given redshift.
Equation 5.2 from P1999.
Parameters
[in] H_0 Hubble constant [km/s/Mpc].
[in] z Redshift.
[in] Omega_M Matter density parameter.
[in] Omega_L Dark energy density parameter.
Returns
The age of the Universe in Gyr.
References python.functions.cosmo2.check_cosmo(), python.functions.extra_math.integ_2arg(), and python.functions.cosmo2.t_H().
def python.functions.cosmo2.check_cosmo (z, Omega_M, Omega_L)
This function checks if the cosmological parameters are valid.
Parameters
[in] z Redshift.
[in] Omega_M Matter density parameter.
[in] Omega_L Dark energy density parameter.
Exceptions
ValueError for invalid z, Omega_M or Omega_L.
def python.functions.cosmo2.d_angdi (z, Omega_M, Omega_L)
This function calculates the angular diameter distance D_A.
Equation 18 from H2000.
Parameters
[in] z Redshift.
[in] Omega_M Matter density parameter.
[in] Omega_L Dark energy density parameter.
Returns
D_A [H0 = c = 1.0].
References python.functions.cosmo2.d_prop().
def python.functions.cosmo2.d_comov (z, Omega_M, Omega_L)
This function calculates the line-of-sight comoving distance D_C.
Equation 15 from H2000.
Parameters
[in] z Redshift.
[in] Omega_M Matter density parameter.
[in] Omega_L Dark energy density parameter.
Returns
D_C [H0 = c = 1.0].
References python.functions.cosmo2.check_cosmo(), python.functions.extra_math.integ_2arg(), and python.functions.extra_math.vinteg_2arg().
def python.functions.cosmo2.d_H (H_0)
This function calculates the Hubble distance D_H in Mpc.
Equation 4 from H2000.
Parameters
[in] H_0 Hubble constant [km/s/Mpc].
Returns
The Hubble distance in Mpc.
def python.functions.cosmo2.d_lum (z, Omega_M, Omega_L)
This function calculates the luminosity distance D_L.
Equation 21 from H2000.
Parameters
[in] z Redshift.
[in] Omega_M Matter density parameter.
[in] Omega_L Dark energy density parameter.
Returns
D_L [H0 = c = 1.0].
References python.functions.cosmo2.d_prop().
def python.functions.cosmo2.d_prop (z, Omega_M, Omega_L)
This function calculates the proper motion distance D_M (transverse comoving distance).
Equation 16 from H2000.
Parameters
[in] z Redshift.
[in] Omega_M Matter density parameter.
[in] Omega_L Dark energy density parameter.
Returns
D_M [H0 = c = 1.0].
References python.functions.cosmo2.d_comov().
def python.functions.cosmo2.dD_prop_dz (z, Omega_M, Omega_L)
This function calculates the derivative of the proper motion distance with respect to redshift dD_M/dz.
Parameters
[in] z Redshift.
[in] Omega_M Matter density parameter.
[in] Omega_L Dark energy density parameter.
Returns
dD_M/dz [H0 = c = 1.0].
References python.functions.cosmo2.d_prop(), and python.functions.cosmo2.E_inv().
def python.functions.cosmo2.dV_comov_dz (z, Omega_M, Omega_L)
This function calculates the one-steradian differential comoving volume dV_C/dz.
Equation 28 from H2000.
Parameters
[in] z Redshift.
[in] Omega_M Matter density parameter.
[in] Omega_L Dark energy density parameter.
Returns
dV_C/dz [H0 = c = 1.0].
References python.functions.cosmo2.d_prop().
def python.functions.cosmo2.E (z, Omega_M, Omega_L)
This function calculates E(z), the Hubble parameter.
Equation 14 from H2000.
Parameters
[in] z Redshift.
[in] Omega_M Matter density parameter.
[in] Omega_L Dark energy density parameter.
Returns
E(z) [H0 = c = 1.0].
References python.functions.cosmo2.check_cosmo().
def python.functions.cosmo2.E_inv (z, Omega_M, Omega_L)
This function calculates 1.0/E(z).
Parameters
[in] z Redshift.
[in] Omega_M Matter density parameter.
[in] Omega_L Dark energy density parameter.
Returns
1.0 / E(z) [H0 = c = 1.0].
References python.functions.cosmo2.E().
def python.functions.cosmo2.rho_crit (H_0, z, Omega_M, Omega_L)
This function calculates the critical density rho_c.
Equation 3.25 from P1999.
Parameters
[in] H_0 Hubble constant [km/s/Mpc].
[in] z Redshift.
[in] Omega_M Matter density parameter.
[in] Omega_L Dark energy density parameter.
Returns
The critical density in kg/m^3.
References python.functions.cosmo2.E().
def python.functions.cosmo2.t_H (H_0)
This function calculates the Hubble time T_H in Gyr.
Equation 3 from H2000.
Parameters
[in] H_0 Hubble constant [km/s/Mpc].
Returns
Hubble time in Gyr.
Exceptions
ValueError for invalid H_0.
def python.functions.cosmo2.v_comov (z, Omega_M, Omega_L)
This function calculates the full comoving volume V_C.
Equation 29 from H2000.
Parameters
[in] z Redshift.
[in] Omega_M Matter density parameter.
[in] Omega_L Dark energy density parameter.
Returns
V_C [H0 = c = 1.0].
References python.functions.cosmo2.d_prop().