python: python.web_code.new_kdtree Namespace Reference
python.web_code.new_kdtree Namespace Reference
Functions
def kdtree
def intersect
def quadratic_knn_search
def search_kdtree
def knn_search
def radius_search
Function Documentation
def python.web_code.new_kdtree.intersect (hrect, r2, centroid)
checks if the hyperrectangle hrect intersects with the
hypersphere defined by centroid and r2
def python.web_code.new_kdtree.kdtree (data, leafsize = 10)
build a kd-tree for O(n log n) nearest neighbour search
input:
    data:       2D ndarray, shape =(ndim,ndata), preferentially C order
    leafsize:   max. number of data points to leave in a leaf
output:
    kd-tree:    list of tuples
def python.web_code.new_kdtree.knn_search (data, K, leafsize = 2048)
find the K nearest neighbours for data points in data,
    using an O(n log n) kd-tree
References python.web_code.new_kdtree.kdtree(), and python.web_code.new_kdtree.search_kdtree().
def python.web_code.new_kdtree.quadratic_knn_search (data, lidx, ldata, K)
find K nearest neighbours of data among ldata
def python.web_code.new_kdtree.radius_search (tree, datapoint, radius)
find all points within radius of datapoint
References python.web_code.new_kdtree.intersect().
def python.web_code.new_kdtree.search_kdtree (tree, datapoint, K)
find the k nearest neighbours of datapoint in a kdtree
References python.web_code.new_kdtree.intersect(), and python.web_code.new_kdtree.quadratic_knn_search().