python: python.halo_methods.nfw Namespace Reference
python.halo_methods.nfw Namespace Reference
Functions
def nfw_proj_sd
Function calculates the NFW profile projected surface density.
def nfw_proj_mass
Function calculates the NFW profile projected mass along a cylinder in units of M(r-2).
def nfw_num_density
NFW number density for given projected radius, scale radius and background density.
def nfw_proj_maxlik_bg
Maximum liklihood for projected NFW with background.
def min_nfw_proj
Minimisation of projected NFW with background density using adaptive grid search.
Function Documentation
def python.halo_methods.nfw.min_nfw_proj (R_proj, r_scale, bg_density = 0.0, fit_bg = True, weights = None)
Minimisation of projected NFW with background density using adaptive grid search.
Parameters
[in] R_proj Projected radius.
[in] r_scale Scale radius.
[in] bg_density Background density.
[in] fit_bg Optional fit to background density.
[in] weights Optional weights.
References python.halo_methods.nfw.nfw_proj_maxlik_bg(), and python.quick_hist.range.
def python.halo_methods.nfw.nfw_num_density (R_proj, r_scale, bg_density)
NFW number density for given projected radius, scale radius and background density.
Parameters
[in] R_proj Projected radius.
[in] r_scale Scale radius.
[in] bg_density Background density.
References python.halo_methods.nfw.nfw_proj_mass().
def python.halo_methods.nfw.nfw_proj_mass (t)
Function calculates the NFW profile projected mass along a cylinder in units of M(r-2).
Equation B1 from MBB2013.
Parameters
[in] t t = R / r_s.
def python.halo_methods.nfw.nfw_proj_maxlik_bg (r_scale_bg, R_proj, weights = None)
Maximum liklihood for projected NFW with background.
Parameters
[in] r_scale_bg Scale radius and background density.
[in] R_proj Projected radius.
[in] weights Optional weights.
References python.halo_methods.nfw.nfw_num_density().
def python.halo_methods.nfw.nfw_proj_sd (t)
Function calculates the NFW profile projected surface density.
Equations 42 and 43 from LM2001.
Parameters
[in] t t = R / r_s.