python: python.pydiag_note Namespace Reference
python.pydiag_note Namespace Reference
Functions
def usage
def file_name_error
def get_rich
def find_galaxy_match
def find_halo_match
def loop_through_matches
def main
Function Documentation
def python.pydiag_note.file_name_error (file_name)
References python.pydiag_note.usage().
def python.pydiag_note.find_galaxy_match (cluster_galaxy_ids, mock_galaxy_ids)
Function to match galaxy IDs between cluster files and mocks
def python.pydiag_note.find_halo_match (halo_ids, cluster_ids, cluster_now)
Function to find the most common Halo ID associated to a given cluster
def python.pydiag_note.get_rich (galaxy_list, unique_galaxy_list)
References python.quick_hist.range.
def python.pydiag_note.loop_through_matches (halo_ids, cluster_ids, unique_cluster_ids)
Function that loops through all cluster to halo matches
References python.pydiag_note.find_halo_match(), and python.quick_hist.range.
def python.pydiag_note.main (argv)
References python.pydiag_note.file_name_error(), python.pydiag_note.find_galaxy_match(), python.pydiag_note.get_rich(), python.pydiag_note.loop_through_matches(), python.functions.comp.nan2one(), python.quick_hist.range, and python.pydiag_note.usage().
def python.pydiag_note.usage ()