python: python.analyz Namespace Reference
python.analyz Namespace Reference
Functions
def usage
def percentile
def std68
def outfrac
def bootstrap
def main
Function Documentation
def python.analyz.bootstrap (data, num_samples, statistic, alpha, limit)
Returns bootstrap estimate of 100.0*(1-alpha) CI for statistic.
def python.analyz.main (argv)
References python.analyz.bootstrap(), python.analyz.outfrac(), python.quick_hist.range, python.analyz.std68(), and python.analyz.usage().
def python.analyz.outfrac (data, limit)
def python.analyz.percentile (N, percent)
def python.analyz.std68 (N)
References python.analyz.percentile().
def python.analyz.usage ()