python: python.gal_split Namespace Reference
python.gal_split Namespace Reference
Functions
def usage
def file_name_error
def main
Function Documentation
def python.gal_split.file_name_error (file_name)
References python.gal_split.usage().
def python.gal_split.main (argv)
References python.gal_split.file_name_error(), and python.gal_split.usage().
def python.gal_split.usage ()